name: kagayaku
description: Kagayaku is a manga reader app.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_feather_icons: ^1.0.3
  flutter_cupertino_settings: ^0.3.0

  json_annotation: ^3.0.1
  built_collection: ^4.3.2
  equatable: ^1.1.1
  html: ^0.14.0+3
  http: ^0.12.1

  flutter_bloc: ^4.0.0
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: false
